image: debian/stable
packages:
    - cmake
    - ncurses-dev
sources:
    - https://github.com/donmccaughey/fiends_and_fortune
tasks:
    - setup: |
        cd fiends_and_fortune
        cmake -S . -B tmp
    - build: |
        cd fiends_and_fortune
        cmake --build tmp --target all test
triggers:
    - action: email
      condition: failure
      to: Don McCaughey <don@donm.cc>

