image: freebsd/latest
packages:
    - cmake
sources:
    - https://github.com/donmccaughey/fiends_and_fortune
tasks:
    - setup: |
        cd fiends_and_fortune
        cmake -S . -B tmp -DWALL=ON
    - build: |
        cd fiends_and_fortune
        cmake --build tmp --target all
        cd tmp
        ctest --output-on-failure
triggers:
    - action: email
      condition: failure
      to: Don McCaughey <don@donm.cc>
