#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if [ -d tmp ]
then
    rm -rf tmp
fi

cmake \
    -S . \
    -B tmp \
    -DADDRESS_SANITIZER=ON \
    -DCOVERAGE=ON \
    -DGRAPH_TARGETS=ON \
    -DWALL=ON

cmake \
    --build tmp \
    --target all test
