name: Tests
on: [push, pull_request]
jobs:
  Coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Packages
        run: |
          sudo apt-get update
          sudo apt-get install libbsd-dev libgpm-dev
      - name: Configure
        run: |
          cmake -S . -B ${{github.workspace}}/tmp -DADDRESS_SANITIZER=ON -DCOVERAGE=ON -DWALL=ON
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/tmp --target all
          cd ${{github.workspace}}/tmp
          ctest --output-on-failure
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          codecov_yml_path: ${{github.workspace}}/.codecov.yml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
  All-Tests-macOS:
    name: All Tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: |
          cmake -S . -B ${{github.workspace}}/tmp -DADDRESS_SANITIZER=ON -DWALL=ON
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/tmp --target all
          cd ${{github.workspace}}/tmp
          ctest --output-on-failure
