name: Tests
on: [push, pull_request]
jobs:
  All-Tests:
    name: All Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B ${{github.workspace}}/tmp -DADDRESS_SANITIZER=ON -DCOVERAGE=ON -DWALL=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/tmp --target all test
      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)
