name: Tests
on: [push, pull_request]
jobs:
  Coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Packages
        run: |
          sudo apt-get update
          sudo apt-get install libbsd-dev
      - name: Configure
        run: |
          cmake -S . -B ${{github.workspace}}/tmp -DCOVERAGE=ON -DWALL=ON
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/tmp --target all test
      - name: Coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
  All-Tests-macOS:
    name: All Tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Packages
        run: |
          brew update
          brew install ncurses
      - name: Configure
        run: |
          cmake -S . -B ${{github.workspace}}/tmp -DHOMEBREW_NCURSES=ON -DWALL=ON
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/tmp --target all test
